// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/lineage/:hash': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lineage/[hash].get').default>>>>
    }
    '/api/lineage': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lineage/index.post').default>>>>
    }
    '/api/onsite/inbred': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/onsite/inbred.post').default>>>>
    }
    '/api/onsite': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/onsite/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}