FROM node:24.0-bookworm-slim AS build
ENV NODE_ENV=development
WORKDIR /app
ARG VERSION=0.0.0-dev
ARG COMMIT_SHA=unknown
ENV VITE_VERSION=$VERSION
ENV VITE_COMMIT_SHA=$COMMIT_SHA
COPY package*.json ./
RUN npm ci
