services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    command: sleep infinity
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - '5173:5173'
      - '3000:3000'
    depends_on:
      - db
    networks:
      - internal

  db:
    image: mariadb:10
    tty: true
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    networks:
      - internal

  breeds:
    build:
      context: .
      dockerfile: ./process-breeds/Dockerfile
    command: sleep infinity
    cap_add:
      - SYS_ADMIN
    volumes:
      - .:/app

  testapp:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build
    command: sleep infinity
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.testing
    depends_on:
      - testdb
    networks:
      - testing

  testdb:
    image: mariadb:10
    tty: true
    ports:
      - '3307:3306'
    env_file:
      - .env.testing
    networks:
      - testing

volumes:
  dbdata:

networks:
  internal:
  testing:
