services:
  app:
    image: ghcr.io/edenchazard/dc-lineage-builder:6.8.1
    command: npm run prod
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - internal
      - dragcave

  db:
    image: mariadb:10
    tty: true
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3306
    networks:
      - internal

volumes:
  dbdata:

networks:
  internal:
  dragcave:
