services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - 5173:5173
      - 3000:3000
    depends_on:
      - db
    networks:
      - internal

  db:
    image: mariadb:10
    tty: true
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3306:3306
    networks:
      - internal

  breeds:
    build:
      context: .
      dockerfile: ./process-breeds/Dockerfile
    command: sleep infinity
    cap_add:
      - SYS_ADMIN
    volumes:
      - .:/app

  testapp:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: sleep infinity
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.testing
    depends_on:
      testdb:
        condition: service_healthy
    networks:
      - testing

  testdb:
    image: mariadb:10
    tty: true
    env_file:
      - .env.testing
    networks:
      - testing
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 4

volumes:
  dbdata:

networks:
  internal:
  testing:
