name: dc-lb_dev
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    command: sleep infinity
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - '5173:5173'
      - '3000:3000'
    depends_on:
      - db
    networks:
      - internal

  db:
    image: mariadb:10
    tty: true
    volumes:
      - ./db/dev:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - internal

  breeds:
    build:
      context: .
      dockerfile: ./process-breeds/Dockerfile
    command: sleep infinity
    cap_add:
      - SYS_ADMIN
    volumes:
      - .:/app

  testapp:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build
    command: sleep infinity
    volumes:
      - .:/app
    depends_on:
      - testdb
    networks:
      - testing
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=linbuilder
      - MYSQL_PASSWORD=linbuilder
      - MYSQL_ROOT_PASSWORD=linbuilder
      - MYSQL_HOST=testdb

  testdb:
    image: mariadb:10
    tty: true
    volumes:
      - ./db/dev:/docker-entrypoint-initdb.d
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: linbuilder
      MYSQL_PASSWORD: linbuilder
      MYSQL_ROOT_PASSWORD: linbuilder
    networks:
      - testing

volumes:
  dbdata:

networks:
  internal:
  testing:
