name: dc-lb_dev
services:
  vue:
    container_name: dc-lb-dev-vue
    build:
      context: ./src/frontend
      dockerfile: ./df.Dockerfile
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    depends_on:
      - db
      - api
    networks:
      - internal

  api:
    container_name: dc-lb-dev-api
    build:
      context: ./src/backend
      dockerfile: ./df.Dockerfile
    depends_on:
      - db
    volumes:
      - ./src/backend:/app
      - /app/node_modules
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
    networks:
      - internal

  db:
    container_name: dc-lb-dev-db
    image: mariadb:10
    tty: true
    volumes:
      - ./src/db/dev:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - internal

  # only for development
  adminer:
    container_name: dc-lb-dev-adminer
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: ${MYSQL_DATABASE}
    ports:
      - 82:8080
    networks:
      - internal

volumes:
  dbdata:

networks:
  internal: