export const dragonGen13 = {
  code: 'FZFet',
  name: 'Alysa Indigo',
  parents: {
    f: {
      code: '9T9BK',
      name: 'Silvana Indigo',
      parents: {},
      breed: 'Placeholder',
      gender: 'f',
      display: 1,
    },
    m: {
      code: 'We50N',
      name: 'Misti Chocolate',
      parents: {
        f: {
          code: 'ij3BH',
          name: 'Ellene Olive',
          parents: {},
          breed: 'Placeholder',
          gender: 'f',
          display: 1,
        },
        m: {
          code: 'Xd569',
          name: 'Eda Coffee',
          parents: {
            f: {
              code: 'e6DDO',
              name: 'Andeee White',
              parents: {},
              breed: 'Placeholder',
              gender: 'f',
              display: 1,
            },
            m: {
              code: 'GQ01Z',
              name: 'Jorrie Plum',
              parents: {
                f: {
                  code: 'nM604',
                  name: 'Betteanne Fuchsia',
                  parents: {},
                  breed: 'Placeholder',
                  gender: 'f',
                  display: 1,
                },
                m: {
                  code: '1dRjM',
                  name: 'Aurelie Teal',
                  parents: {
                    m: {
                      code: 'jkOcV',
                      name: 'Feliza Scarlet',
                      parents: {
                        m: {
                          code: 'ZouJK',
                          name: 'Lexie Indigo',
                          parents: {
                            m: {
                              code: '6Xh6k',
                              name: 'Candida Amaranth',
                              parents: {
                                m: {
                                  code: '91oN9',
                                  name: 'Theadora Gray',
                                  parents: {
                                    m: {
                                      code: 'HVzdi',
                                      name: 'Cindra Gold',
                                      parents: {
                                        m: {
                                          code: 'MFcgW',
                                          name: 'Lavinie Apricot',
                                          parents: {
                                            m: {
                                              code: '4Nm3d',
                                              name: 'Willow Lime',
                                              parents: {
                                                m: {
                                                  code: '5lpbL',
                                                  name: 'Carly Peach',
                                                  parents: {},
                                                  breed: 'Placeholder',
                                                  gender: 'm',
                                                  display: 1,
                                                },
                                                f: {
                                                  code: 'peRMT',
                                                  name: 'Allison Magenta',
                                                  parents: {},
                                                  breed: 'Placeholder',
                                                  gender: 'f',
                                                  display: 1,
                                                },
                                              },
                                              breed: 'Placeholder',
                                              gender: 'm',
                                              display: 1,
                                            },
                                            f: {
                                              code: 'zhzyR',
                                              name: 'Marielle Copper',
                                              parents: {},
                                              breed: 'Placeholder',
                                              gender: 'f',
                                              display: 1,
                                            },
                                          },
                                          breed: 'Placeholder',
                                          gender: 'm',
                                          display: 1,
                                        },
                                        f: {
                                          code: '8nBEz',
                                          name: 'Scarlet Teal',
                                          parents: {},
                                          breed: 'Placeholder',
                                          gender: 'f',
                                          display: 1,
                                        },
                                      },
                                      breed: 'Placeholder',
                                      gender: 'm',
                                      display: 1,
                                    },
                                    f: {
                                      code: '41JzU',
                                      name: 'Jsandye Coral',
                                      parents: {},
                                      breed: 'Placeholder',
                                      gender: 'f',
                                      display: 1,
                                    },
                                  },
                                  breed: 'Placeholder',
                                  gender: 'm',
                                  display: 1,
                                },
                                f: {
                                  code: '8vaAA',
                                  name: 'Diahann Amaranth',
                                  parents: {},
                                  breed: 'Placeholder',
                                  gender: 'f',
                                  display: 1,
                                },
                              },
                              breed: 'Placeholder',
                              gender: 'm',
                              display: 1,
                            },
                            f: {
                              code: 'OY52d',
                              name: 'Carmelle Blush',
                              parents: {},
                              breed: 'Placeholder',
                              gender: 'f',
                              display: 1,
                            },
                          },
                          breed: 'Placeholder',
                          gender: 'm',
                          display: 1,
                        },
                        f: {
                          code: 'q2zkJ',
                          name: 'Winona Violet',
                          parents: {},
                          breed: 'Placeholder',
                          gender: 'f',
                          display: 1,
                        },
                      },
                      breed: 'Placeholder',
                      gender: 'm',
                      display: 1,
                    },
                    f: {
                      code: '2KpPw',
                      name: 'Ginnifer Apricot',
                      parents: {},
                      breed: 'Placeholder',
                      gender: 'f',
                      display: 1,
                    },
                  },
                  breed: 'Placeholder',
                  gender: 'm',
                  display: 1,
                },
              },
              breed: 'Placeholder',
              gender: 'm',
              display: 1,
            },
          },
          breed: 'Placeholder',
          gender: 'm',
          display: 1,
        },
      },
      breed: 'Placeholder',
      gender: 'm',
      display: 1,
    },
  },
  breed: 'Placeholder',
  gender: 'm',
  display: 1,
};

export const dragonGen2 = {
  code: 'uIfWm',
  name: 'Corry Indigo',
  parents: {
    m: {
      code: 'WuTUL',
      name: 'Rakel Orange',
      parents: {},
      breed: 'Placeholder',
      gender: 'm',
      display: 1,
    },
    f: {
      code: 'Vqfvy',
      name: 'Millicent Red',
      parents: {},
      breed: 'Placeholder',
      gender: 'f',
      display: 1,
    },
  },
  breed: 'Placeholder',
  gender: 'm',
  display: 1,
};

export const dragonWithGhostBreedName = {
  code: 'uIfWm',
  name: 'Corry Indigo',
  parents: {
    m: {
      code: 'WuTUL',
      name: 'Rakel Orange',
      parents: {},
      breed: 'ABCD TEST XYZ',
      gender: 'm',
      display: 1,
    },
    f: {
      code: 'Vqfvy',
      name: 'Millicent Red',
      parents: {},
      breed: 'Placeholder',
      gender: 'f',
      display: 1,
    },
  },
  breed: 'Placeholder',
  gender: 'm',
  display: 1,
};
