name: Import and Commit Breed Data

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'dragcave-breed-data commit SHA to use'
        required: true
        type: string

jobs:
  import-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create dummy env
        run: touch .env && cat .env.testing >> .env

      - name: Start app container
        run: docker compose up app -d

      - name: Update breeds
        run: docker compose exec -T app sh -c "npm run update-breeds -- ${{ inputs.sha }}"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ github.ref_name }}
          branch: import-breed-data-${{ inputs.sha }}
          commit-message: |-
            (chore) import and commit breed data

            Source: https://github.com/edenchazard/dragcave-breed-data/commit/${{ inputs.sha }}
          title: |-
            (chore) import and commit breed data
          body: |-
            Source: https://github.com/edenchazard/dragcave-breed-data/commit/${{ inputs.sha }}
          add-paths: |
            app/shared/breed-definitions.ts
            app/assets/tile-rendering/*.css
          delete-branch: true
